import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

// Prepended to the built main.js so anyone opening the bundled output knows it's generated.
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// `node esbuild.config.mjs production` (see package.json "build" script) vs plain
// `node esbuild.config.mjs` (the "dev" script) for a watch build with inline sourcemaps.
const prod = process.argv[2] === 'production';

// Bundles src/main.ts -> main.js. Obsidian/Electron/CodeMirror packages are marked
// external since the host app provides them at runtime; bundling them would bloat
// the plugin and risk duplicate module instances.
const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
  ],
  format: 'cjs',
  target: 'es2021',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
});

if (prod) {
  // One-shot minified build for release.
  await context.rebuild();
  process.exit(0);
} else {
  // Long-running watch mode for local development.
  await context.watch();
}
